### ISSUE TITLE
Имена колонок: `column-image`

### ISSUE THREAD

**Issue by betadog** [ova777/dao#1]
MYSQL позволяет иметь подобные имена колонок, но при insert/update формируются имена подстановочных переменных :daosetcolumn-image

Необходимо сделать 
$_param = ':daoset'.preg_replace('/-/','',$k);
или
$_param = ':daoset'.str_replace('-','',$k);

**Comment by ovaunit** [comment]
Спасибо за замечание. Исправил.
Но в Вашей реализации нельзя иметь колонки `column-image` и `columnimage` в одной таблице.
Поэтому сделал ':daoset'+хэш от названия колонки
